sensors:
  - filtered_cloud_topic: filtered_cloud
    min_range: 0.0
    max_range: 2.0
    padding_offset: 0.1
    padding_scale: 1.0
    point_cloud_topic: /octomap/points
    point_subsample: 1
    sensor_plugin: occupancy_map_monitor/PointCloudOctomapUpdater
