ARM_GROUP: "whole_body"
ARM_JOINTS: []
ARM_GRASP: []
HEAD_GROUP: ""
HEAD_JOINTS: []
HEAD_LOOK_DOWN: []
HEAD_LOOK_FRONT: []
HEAD_LEFT: []
HEAD_RIGHT: []
GRIPPER_GROUP: "hand"
GRIPPER_JOINTS: []
GRIPPER_OPEN: []
GRIPPER_CLOSED: []
GRASP_POSTURES_FRAME_ID: "hand_eef_link"
ALLOW_CONTACT: [
  "hand_eef_link",
  "hand_palm_link",
  "hand_motor_dummy_link",
  "hand_l_proximal_link",
  "hand_l_spring_proximal_link",
  "hand_l_mimic_distal_link",
  "hand_l_distal_link",
  "hand_l_finger_tip_frame",
  "hand_l_finger_vacuum_frame",
  "hand_r_proximal_link",
  "hand_r_spring_proximal_link",
  "hand_r_mimic_distal_link",
  "hand_r_distal_link",
  "wrist_roll_link"
  "hand_r_finger_tip_frame",
  "<octomap>",
  "base_link",
  "base_l_drive_wheel_link",
  "base_r_drive_wheel_link"
]
CAMERA_DEPTH_FRAME: ""
